# Generated by Django 4.1 on 2022-11-22 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_producto", models.CharField(max_length=30)),
                ("stock", models.IntegerField()),
                ("precio", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TipoProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categoria", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="TipoUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Venta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(null=True)),
                ("precio_iva", models.IntegerField()),
                ("precio_total", models.IntegerField()),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.producto"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usuario", models.CharField(max_length=15)),
                ("nombre", models.CharField(max_length=15)),
                ("apellido", models.CharField(max_length=15)),
                ("mail", models.CharField(max_length=30)),
                ("password", models.CharField(max_length=15)),
                ("telefono", models.IntegerField()),
                ("ciudad", models.CharField(max_length=15)),
                ("direccion", models.CharField(max_length=30)),
                ("sexo", models.CharField(max_length=15)),
                (
                    "tipo_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.tipousuario",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="producto",
            name="tipo_producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.tipoproducto"
            ),
        ),
    ]
