# Generated by Django 4.1 on 2022-11-29 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_marca_nombre_alter_producto_descripcion_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Venta",
        ),
    ]
